#!/bin/sh

usage_exit() {
  echo "Usage: $0 [-o runfile] file ..." 1>&2
}

fext="${1##*.}"

while getopts :o:h OPT
do
  case $OPT in
    o) fext="${3##*.}"
       if [ "x$fext" = "xc" ]; then 
         gcc -o $2 $3 && ./$2 
       else if [ "x$fext" = "xcpp" ]; then
         g++ -o $2 $3 && ./$2
       fi fi
       shift $(($OPTIND - 1))
       exit ;;
    h) echo "[help]"
       usage_exit
       shift $(($OPTIND - 1))
       exit ;;
    *) usage_exit
       shift $(($OPTIND - 1))
       exit ;;
  esac
done

if [ "x$fext" = "xc" ]; then
  gcc $1 && ./a.out
else if [ "x$fext" = "xcpp" ]; then
  g++ $1 && ./a.out
fi fi
